### ISSUE TITLE
Acorn needs to be updated

### ISSUE THREAD

**Issue by BarryCarlyon** [pugjs/is-expression#15]
I received a notification that acorn needs to be updated

https://github.com/advisories/GHSA-7fhm-mqm4-2wp7

I use pug, which has a dependancy of `is-expression` which uses acorn which needs to be updated to at least 5.7.4.

**Comment by BarryCarlyon** [comment]
I have observed that gatekeeper is trying to issue automated PR's but no one has accepted then

https://github.com/pugjs/is-expression/pull/10

**Comment by nitmws** [comment]
I use pug, including is-expression, in some web apps too and also got complaints about "a potential security vulnerability" based on the old acorn ^4.x.x" version in the dependencies. Acorn 5.7.4, 6.4.1 or 7.1.1 should fix that.

**Comment by skipper09** [comment]
I am awaiting resolution of this as well.

**Comment by warerebel** [comment]
I have raised pull request #18 to update Acorn

**Comment by skipper09** [comment]
Kind of a novice here, but will this published on npm?

**Comment by nitmws** [comment]
First the pull request must be committed by the PugJS team and a new release may be created. Then this update must be handed over to npm, I guess this will be done by script. E.g. @ForbesLindesay is active on keeping PugJS in sync with external modules.

**Comment by ForbesLindesay** [comment]
This security does not and never did impact the version of acorn used by is-expression.
